name: 🚀 Deploy Version

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  cortex-m3: # replace with the correct arch
    uses: libhal/ci/.github/workflows/deploy.yml@5.x.y
    with:
      arch: cortex-m3 # replace with the correct arch
      version: ${{ inputs.version }}
      os: baremetal
      compiler: gcc
      compiler_version: 12.3
      compiler_package: arm-gnu-toolchain
    secrets: inherit

  cortex-m4f: # remove if only one architecture is used
    uses: libhal/ci/.github/workflows/deploy.yml@5.x.y
    with:
      arch: cortex-m4f # replace with the correct arch
      version: ${{ inputs.version }}
      os: baremetal
      compiler: gcc
      compiler_version: 12.3
      compiler_package: arm-gnu-toolchain
    secrets: inherit
